### ISSUE TITLE
ERROR in ./node_modules/@fusioncharts/features/src/export-module/export.js

### ISSUE THREAD

**Issue by TayyabK** [fusioncharts/angular-fusioncharts#69]
Module not found: Error: Can't resolve '../../../fc-utils/src/type/array-has-content'.
Angular fails to compile after updating to fusion chart version 3.14.1 giving this error.

**Comment by soumyasdutta** [comment]
Hey,
The FusionCharts version 3.14.1 is working properly with FusionCharts-angular plugin at our end.
Could you please replicate the issue in the following sample https://codesandbox.io/s/jzqwr276y3 for further investigations.

**Comment by soumyasdutta** [comment]
There is no compilation error we are getting while implementing FusionCharts 3.14.1 in Angular environment at our end. Kindly, please replicate the issue in a scaled down sample for further investigations.
Also please note please check whether you have included ExcelExport within module.ts as mentioned below.
import * as ExcelExport from "fusioncharts/fusioncharts.excelexport";

**Comment by burnhamrobertp** [comment]
I have the same underlying issue in a fairly established repository as what @TayyabK  describes. I've tried to reproduce it in a standalone repo and am unable to, however the same underlying cause exists in both situations: the path to the `arrayHasContent` import simply does not exist. **Even in the small repo where everything works normally!**

4.13.0 works using the exact same code, but 4.13.1 results in the `Can't resolve '../../../fc-utils/src/type/array-has-content'` error.

Both have the same code in respect to the `export.js` file so both are executing the code `import arrayHasContent from"../../../fc-utils/src/type/array-has-content"` but 4.13.0 works perfectly fine while 4.13.1 breaks during compile.

So my question is...how does 4.13.0 work at all, when its importing a file that clearly doesn't exist in the file system. How does this work?

**Comment by soumyasdutta** [comment]
> s
could you provide us a scaled down sample replicating the issue for further investigation as the issue is not getting replicated at our end.

You may share a GitHub repo putting the sample app.

**Comment by burnhamrobertp** [comment]
I cannot, I have not been able to. If you're able to answer the question at the bottom of my last comment, I should be able to reverse engineer where its going off the rails.

**Comment by priyanjitdey94** [comment]
@TayyabK @burnhamrobertp It's fixed in the latest version of fusioncharts. Please check and let me know.

**Comment by ayanonly1** [comment]
This message serves as confirmation that you are now successfully registered in our support center.

Registered Email: reply@reply.github.com
Password: h2axpwnyn0

You can visit the Support Desk at any time by going to http://help.fusioncharts.com/

Please do let us know if you have any questions.

Regards,


FusionCharts Team
------------------------------------------------------
Support Center: http://help.fusioncharts.com/index.php?

**Comment by ayanonly1** [comment]
Dear fusioncharts/angular-fusioncharts,

Thanks for your mail and interest in FusionCharts suite of products.

This is an automated response to let you know that we've received your request. Our support staff is currently reviewing it, and would get in touch with you soon. Meanwhile, you may use our self-help options like Community Forums, Knowledge base & Online Documentation at http://support.fusioncharts.com/

Please note the information below, as it will allow you to track the progress of your request online.

	Ticket ID: 336591
	Subject: Re: [fusioncharts/angular-fusioncharts] ERROR in ./node_modules/@fusioncharts/features/src/export-module/export.js (#69)
	Department: General
	Type: Issue
	Status: Open
	Priority: Medium

You can check the status of or reply to this ticket online at: http://help.fusioncharts.com/index.php?/Tickets/Ticket/View/336591

Thanks,

FusionCharts Team


------------------------------------------------------
Support Center: http://help.fusioncharts.com/index.php?
